Create the following Numpy array of 32-bit integers

    array([[1, 1, 1, 1, 1],
           [0, 1, 1, 1, 1],
           [0, 0, 1, 1, 1],
           [0, 0, 0, 1, 1],
           [0, 0, 0, 0, 1]])



In [141]:
import numpy as np
from numpy import array
x = 1* np.fromfunction(lambda i,j:j>=i,(5,5),dtype=np.int32)
answer = x # replace None with the Numpy array described above
# x = np.array([5,5], dtype=np.int16)




In [142]:
print(answer)

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]


Create the following Numpy array of 16-bit integers

    array([[ 1,  2,  3,  4,  5],
           [ 0,  6,  7,  8,  9],
           [ 0,  0, 10, 11, 12],
           [ 0,  0,  0, 13, 14],
           [ 0,  0,  0,  0, 15]])

In [143]:
counter = 1
for i in range(15):
    x = 1* np.fromfunction(lambda i,j:j>=i,(5,5),dtype=np.int16)
for i in range(5):
    for j in range(5):
        if x[i][j] == 0:
            pass
        else:
            x[i][j] = counter
            counter +=1
answer = x # replace None with the Numpy array described above


In [144]:
print(answer)

[[ 1  2  3  4  5]
 [ 0  6  7  8  9]
 [ 0  0 10 11 12]
 [ 0  0  0 13 14]
 [ 0  0  0  0 15]]


Given the following two-dimensional array, set the diagonal element to the average of the columns in each respective row not counting the diagonal element in each row. Note that the diagonal element itself is not part of the calculation. It is just a placeholder for the result.

    [[0,   3, 14, 13, 12],
     [13,  0,  8,  5, 11],
     [11, 11,  0, 12, 10],
     [11, 12,  1,  0, 10],
     [13, 12, 11,  4,  0]]
     
In this case, your answer should look like the following

    [[ 10.5 ,   3.  ,  14.  ,  13.  ,  12.  ],
     [ 13.  ,   9.25,   8.  ,   5.  ,  11.  ],
     [ 11.  ,  11.  ,  11.  ,  12.  ,  10.  ],
     [ 11.  ,  12.  ,   1.  ,   8.5 ,  10.  ],
     [ 13.  ,  12.  ,  11.  ,   4.  ,  10.  ]]

In the general case, the diagonal elements won't necessarily be equal to zero like they are here!

In [145]:
from __future__ import division
import numpy as np
from numpy import float
def average_into_diagonal(x):
    '''
    return average of non-diagonal elements with values filled into the diagonal
    
    :param x: square two-dimensional input array
    :type x: numpy array
    :returns: numpy array

    '''
    assert isinstance(x,np.ndarray),'input is not a array type'
    assert x.ndim == 2,'input matrix is not a 2D matrix'
    assert x.shape[0] == x.shape[1],'input matrix is not a square shape'
    x = x.astype(float)
    n = x.shape[0]  
    for i in range(n): 
        sumOfRow = 0
        for j in range(n):
            if i == j:
                pass
            else:
                sumOfRow += x[i][j]
            x[i][i] = sumOfRow/4.0
    return x


In [146]:
x = [[0,   3, 14, 13, 12],
 [13,  0,  8,  5, 11],
 [11, 11,  0, 12, 10],
 [11, 12,  1,  0, 10],
 [13, 12, 11,  4,  0]]

x = np.asarray(x)
newX = average_into_diagonal(x)
print(newX)
            

<class 'numpy.ndarray'>
[[ 10.5    3.    14.    13.    12.  ]
 [ 13.     9.25   8.     5.    11.  ]
 [ 11.    11.    11.    12.    10.  ]
 [ 11.    12.     1.     8.5   10.  ]
 [ 13.    12.    11.     4.    10.  ]]
